name: RDP_COFFIN

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://uc48c2339ce2b32bf113361c5010.dl.dropboxusercontent.com/cd/0/get/BUE3tBKZJqNHWAc6_yHBcT1tLKc7VzPe2GJo7MS_URWXSdFsgRQJRzalttpIIF0brgtJD126g-NiBU6gXGpXjjGb6LTZ8VZ-fBP23ZFegLUwB2hBIZaOVJ7fthAe9WpFuJ2xMlYQnr44DzJPsqeQTF9Y/file?dl=1# -OutFile ngrok.exe
        Invoke-WebRequest https://ucec480df52c727c58acd07aa28e.dl.dropboxusercontent.com/cd/0/get/BUG9zJ5eA8ESUaisnDbQOiUz_bPC5lhjizh6PL6RP_kx2IUdsaAWbPJmGRDoXUH3AHcJW40cOgRjziwq4YU2xuFYWJask3X3oZJ0WorRIskDa-1PySDKkHtDkhcDhBMLDiFV5Qr6bu77fQCRftkT-qh0/file# -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://ucf5ebabacd383231948f9852d20.dl.dropboxusercontent.com/cd/0/get/BUGMZGrmt04ufqzU49t43s6wE5sNqjJHmfc8ye-is5F5uwfYvKxrnK9dKyZh2W8WlN_50As3iDl_igbkN3BwIw4cmoSvYldJbjpfqBTkxd1ULQdHlEYdp8HdFdEv7rFmtYBFX1io9UwN05ZecS85V8Ed/file# -OutFile NGROK-US.bat
        Invoke-WebRequest https://uc416e8a95a2b045a6454043a532.dl.dropboxusercontent.com/cd/0/get/BUECy9YUpWHsINKjS52eiKBWQSxFoi88kYImEzB_gnNO4nk4mYlhXDel3xKWv81wkKT-1gvFVA0r15jjHjHumZZ_5LzD42C6LNEcRF_pyk_CGqajh3LAHwduZpd0a3yDSEPKBLpAaZqfhIja8-fJOQqh/file# -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://ucedb7a14b32174c0252d03c89a3.dl.dropboxusercontent.com/cd/0/get/BUFMU075HqWDBbLw3kn3LfeH8w2Jaic5WpHJhRbscdp269ScA2rWNQ2O_tsuE74v5DCXmSqQz1fQyky7q51EydkGEBaAEOR3X1tBJhAJU5692Ulo5ZMts6PTQj58Ix65D1EgDol40wsgU8rQ8x37csvB/file# -OutFile loop.bat
    - name: Make YML file for NGROK.
      run: start NGROK-US.bat
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: sc start ngrok
    - name: Connect to your RDP 2core-7GB Ram.
      run: cmd /c NGROK-CHECK.bat
    - name: All Done! You can close Tab now! Maximum VM time:6h.
      run: cmd /c loop.bat 
